### ISSUE TITLE
exited with code 73

### ISSUE THREAD

**Issue by iloveyo123u1** [celery/django-celery-beat#16]
hi

my dear friend

i have a question

docker+django+django-celery-beat+django-celery-work

when i use django-admin edit Periodic tasks
django-celery-beat must restart to update Periodic tasks 

so

i use shipyard https://github.com/shipyard/shipyard  restart docker container

every time restart docker container, it return **exited with code 73**

...

long time ...

delete  celerybeat.pid

it's ok 

when i use docker and i stop docker , why not auto delete  celerybeat.pid ?

my  **docker-compose.yml**

---------------------

```
version: '2'
services:
  nginx:
    build: dockerfile/nginx1
    restart: always
    volumes:
      - ./www/:/www/:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - "api1"

  rabbit:
    image: rabbitmq:3.6
    ports:
      - "5672:5672"
      - "15672:15672"

  api1:
    build: dockerfile/django_api1
    restart: always
    ports:
        - "8000:8000"
    volumes:
        - ./api1/:/api1
    command: sh -c 'cd /api1 && gunicorn --workers=5 --bind 0.0.0.0:8000 api1.wsgi'

  celery_worker:
    build: dockerfile/django_api1
    command: sh -c 'cd /api1 && celery -A api1 worker -l info'
    volumes_from:
      - api1
    depends_on:
      - api1
      - rabbit
    links:
      - rabbit

  celery_beat:
    build: dockerfile/django_api1
    command: sh -c 'cd /api1 && celery -A api1 beat -l info -S django'
    volumes_from:
      - api1
    depends_on:
      - api1
      - rabbit
    links:
      - rabbit
```
