### ISSUE TITLE
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'

### ISSUE THREAD

**Issue by buffmomoeveryday** [celery/django-celery-beat#871]
## Django Settings
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 60 * 2
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

## Package Version
amqp                          5.3.1
asgiref                       3.8.1
attrs                         25.3.0
autopep8                      2.3.2
billiard                      4.2.1
**celery                        5.5.1**
certifi                       2025.1.31
cffi                          1.17.1
charset-normalizer            3.4.1
click                         8.1.8
click-didyoumean              0.3.1
click-plugins                 1.1.1
click-repl                    0.3.0
colorama                      0.4.6
cryptography                  44.0.2
defusedxml                    0.7.1
**django                        5.2**
django-allauth                65.7.0
**django-celery-beat            2.1.0
django-celery-results         2.5.1**
django-cors-headers           4.7.0
django-extensions             3.2.3
django-filter                 25.1
django-guardian               2.4.0
django-picklefield            3.3
django-q2                     1.7.6
django-redis                  5.4.0
django-rest-framework         0.1.0
django-silk                   5.3.2
django-storages               1.14.6
django-timezone-field         4.2.3
djangorestframework           3.16.0
djangorestframework-simplejwt 5.5.0
djoser                        2.3.1
drf-spectacular               0.28.0
gprof2dot                     2024.6.6
gunicorn                      23.0.0
idna                          3.10
inflection                    0.5.1
jsonschema                    4.23.0
jsonschema-specifications     2024.10.1
kombu                         5.5.2
oauthlib                      3.2.2
packaging                     24.2
prompt-toolkit                3.0.50
psycopg2-binary               2.9.10
pycodestyle                   2.13.0
pycparser                     2.22
pyjwt                         2.9.0
python-crontab                3.2.0
python-dateutil               2.9.0.post0
python-decouple               3.8
python3-openid                3.2.0
pytz                          2025.2
pyyaml                        6.0.2
redis                         5.2.1
referencing                   0.36.2
requests                      2.32.3
requests-oauthlib             2.0.0
rpds-py                       0.24.0
six                           1.17.0
social-auth-app-django        5.4.3
social-auth-core              4.5.6
sqlparse                      0.5.3
typing-extensions             4.13.1
tzdata                        2025.2
uritemplate                   4.1.1
urllib3                       2.3.0
vine                          5.1.0
wcwidth                       0.2.13
whitenoise                    6.9.0

## Docker Compose

```yaml
services:
  postgres:
    restart: unless-stopped
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network

  redis:
    restart: unless-stopped
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  web:
    restart: unless-stopped
    entrypoint: "/app/entrypoint.sh"
    build:
      context: .
    command: [ "uv", "run", "gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "${GUNICORN_WORKERS}", "--timeout", "${GUNICORN_TIMEOUT}", "--log-level", "info", "--reload" ]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - postgres
      - redis
    networks:
      - network

  beat:
    restart: unless-stopped
    build:
      context: .
    command: [ "/bin/sh", "-c", "uv run celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler " ]
    volumes:
      - .:/app
    depends_on:
      - web
      - postgres
      - celery
    networks:
      - network

  celery:
    restart: unless-stopped
    build:
      context: .
    command: [ "/bin/sh", "-c", "uv run   celery -A core  worker -l info" ]
    volumes:
      - .:/app
    depends_on:
      - web
      - postgres
      - redis
    networks:
      - network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - network

volumes:
  pg_data:
  redis_data:
  static_volume:
  media_volume:


networks:
  network:
    driver: bridge
    name: network
```

## Error Logs

2025-04-09 13:01:00 celery beat v5.5.1 (immunity) is starting.
2025-04-09 13:01:03 __    -    ... __   -        _
2025-04-09 13:01:03 LocalTime -> 2025-04-09 07:16:03
2025-04-09 13:01:03 Configuration ->
2025-04-09 13:01:03     . broker -> redis://:**@redis:6379/1
2025-04-09 13:01:03     . loader -> celery.loaders.app.AppLoader
2025-04-09 13:01:03     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
2025-04-09 13:01:03 
2025-04-09 13:01:03     . logfile -> [stderr]@%INFO
2025-04-09 13:01:03     . maxinterval -> 5.00 seconds (5s)
2025-04-09 13:01:03 [2025-04-09 07:16:03,470: INFO/MainProcess] beat: Starting...
2025-04-09 13:01:03 [2025-04-09 07:16:03,557: ERROR/MainProcess] Cannot add entry 'celery.backend_cleanup' to database schedule: AttributeError("'zoneinfo.ZoneInfo' object has no attribute 'localize'"). Contents: {'task': 'celery.backend_cleanup', 'schedule': <crontab: 0 4 * * * (m/h/dM/MY/d)>, 'options': {'expire_seconds': 43200}}
2025-04-09 13:01:03 Traceback (most recent call last):
2025-04-09 13:01:03   File "/.venv/lib/python3.12/site-packages/django_celery_beat/schedulers.py", line 320, in update_from_dict
2025-04-09 13:01:03     entry = self.Entry.from_entry(name,
2025-04-09 13:01:03             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-04-09 13:01:03   File "/.venv/lib/python3.12/site-packages/django_celery_beat/schedulers.py", line 179, in from_entry
2025-04-09 13:01:03     return cls(PeriodicTask._default_manager.update_or_create(
2025-04-09 13:01:03            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-04-09 13:01:03   File "/.venv/lib/python3.12/site-packages/django_celery_beat/schedulers.py", line 93, in __init__
2025-04-09 13:01:03     model.last_run_at = self._default_now()
2025-04-09 13:01:03                         ^^^^^^^^^^^^^^^^^^^
2025-04-09 13:01:03   File "/.venv/lib/python3.12/site-packages/django_celery_beat/schedulers.py", line 143, in _default_now
2025-04-09 13:01:03     now = now.tzinfo.localize(now.replace(tzinfo=None))
2025-04-09 13:01:03           ^^^^^^^^^^^^^^^^^^^
2025-04-09 13:01:03 AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'
